theme = "apollo"
base_url = "https://yashvardhan.me"
# title = "Yashvardhan"
description = ""
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

# [search]
# include_title = true
# include_description = true
# include_path = true
# include_content = true
# index_format = "elasticlunr_json"

[extra]
toc = false
use_cdn = false
favicon = "/icon/favicon.png"
theme = "auto"
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/home", url = "/", weight=1},
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    # { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "github", url = "https://www.linkedin.com/in/yashvardhan-60b3a5184/", icon = "linkedin" },
    { name = "github", url = "https://github.com/yashvardhan-verma/", icon = "github" },
    { name = "twitter", url = "https://twitter.com/yashvrdhnx", icon = "twitter" },
]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

